import { CategoryProps } from '@/components/CategoryItem';

export const CATEGORIES: CategoryProps[] = [
  {
    title: 'Semua',
    isChecked: false,
  },
  {
    title: 'Seminar',
    isChecked: false,
  },
  {
    title: 'Konser',
    isChecked: false,
  },
  {
    title: 'Horor',
    isChecked: false,
  },
  {
    title: 'Komedi',
    isChecked: false,
  },
  {
    title: 'Olahraga',
    isChecked: false,
  },
  {
    title: 'Pameran',
    isChecked: false,
  },
];

export const UPCOMING = [
  {
    id: 1,
    name: 'SUM 41 TOUR OF THE SETTING SUM FINAL TOUR',
    slug: 'SUM-41-TOUR-OF-THE-SETTING-SUM-FINAL-TOUR',
    img: '/1.jpg',
    category: 'Semua',
    location: 'Bandung',
    created_at: '2022-02-22',
    price: 0,
    rating: 4,
    type: 'Free',
    status: 'Tersedia Sekarang',
  },
  {
    id: 2,
    name: 'IBL TOKOPEDIA - GAME 3 - PACIFIC CAESAR SURABAYA VS BIMA PERKASA JOGJA',
    slug: 'IBL-TOKOPEDIA-GAME-3-PACIFIC-CAESAR-SURABAYA-VS-BIMA-PERKASA-JOGJA',
    img: '/2.webp',
    category: 'Semua',
    location: 'Jawa Timur',
    created_at: '2022-02-22',
    price: 50000,
    rating: 4,
    type: 'Paid',
    status: 'Tersedia Sekarang',
  },
  {
    id: 3,
    name: 'IVE THE 1ST WORLD TOUR <SHOW WHAT i HAVE> IN JAKARTA',
    slug: 'IVE-THE-1ST-WORLD-TOUR-<SHOW-WHAT-i-HAVE>-IN-JAKARTA',
    img: '/3.webp',
    category: 'Semua',
    location: 'Banten',
    created_at: '2022-02-22',
    price: 1225000,
    rating: 4,
    type: 'Paid',
    status: 'Tersedia Sekarang',
  },
  {
    id: 4,
    name: 'CHANYEOL FANCON TOUR "THE ETERNITY" IN JAKARTA',
    slug: 'CHANYEOL-FANCON-TOUR-"THE-ETERNITY"-IN-JAKARTA',
    img: '/4.webp',
    category: 'Semua',
    location: 'Banten',
    created_at: '2022-02-22',
    price: 1620000,
    rating: 4,
    type: 'Paid',
    status: 'Tersedia Sekarang',
  },
];

export const EVENTS = [
  {
    id: 1,
    name: 'SUM 41 TOUR OF THE SETTING SUM FINAL TOUR',
    slug: 'SUM-41-TOUR-OF-THE-SETTING-SUM-FINAL-TOUR',
    img: '/1.jpg',
    category: 'Semua',
    location: 'Bandung',
    created_at: '2022-02-22',
    price: 0,
    rating: 4,
    type: 'Free',
    status: 'Tersedia Sekarang',
  },
  {
    id: 2,
    name: 'IBL TOKOPEDIA - GAME 3 - PACIFIC CAESAR SURABAYA VS BIMA PERKASA JOGJA',
    slug: 'IBL-TOKOPEDIA-GAME-3-PACIFIC-CAESAR-SURABAYA-VS-BIMA-PERKASA-JOGJA',
    img: '/2.webp',
    category: 'Semua',
    location: 'Jawa Timur',
    created_at: '2022-02-22',
    price: 50000,
    rating: 4,
    type: 'Paid',
    status: 'Tersedia Sekarang',
  },
  {
    id: 3,
    name: 'IVE THE 1ST WORLD TOUR <SHOW WHAT i HAVE> IN JAKARTA',
    slug: 'IVE-THE-1ST-WORLD-TOUR-<SHOW-WHAT-i-HAVE>-IN-JAKARTA',
    img: '/3.webp',
    category: 'Semua',
    location: 'Banten',
    created_at: '2022-02-22',
    price: 1225000,
    rating: 4,
    type: 'Paid',
    status: 'Tersedia Sekarang',
  },
  {
    id: 4,
    name: 'CHANYEOL FANCON TOUR "THE ETERNITY" IN JAKARTA',
    slug: 'CHANYEOL-FANCON-TOUR-"THE-ETERNITY"-IN-JAKARTA',
    img: '/4.webp',
    category: 'Semua',
    location: 'Banten',
    created_at: '2022-02-22',
    price: 1620000,
    rating: 4,
    type: 'Paid',
    status: 'Tersedia Sekarang',
  },
  {
    id: 4,
    name: 'CHANYEOL FANCON TOUR "THE ETERNITY" IN JAKARTA',
    slug: 'CHANYEOL-FANCON-TOUR-"THE-ETERNITY"-IN-JAKARTA',
    img: '/4.webp',
    category: 'Semua',
    location: 'Banten',
    created_at: '2022-02-22',
    price: 1620000,
    rating: 4,
    type: 'Paid',
    status: 'Tersedia Sekarang',
  },
  {
    id: 4,
    name: 'CHANYEOL FANCON TOUR "THE ETERNITY" IN JAKARTA',
    slug: 'CHANYEOL-FANCON-TOUR-"THE-ETERNITY"-IN-JAKARTA',
    img: '/4.webp',
    category: 'Semua',
    location: 'Banten',
    created_at: '2022-02-22',
    price: 1620000,
    rating: 4,
    type: 'Paid',
    status: 'Tersedia Sekarang',
  },
  {
    id: 4,
    name: 'CHANYEOL FANCON TOUR "THE ETERNITY" IN JAKARTA',
    slug: 'CHANYEOL-FANCON-TOUR-"THE-ETERNITY"-IN-JAKARTA',
    img: '/4.webp',
    category: 'Semua',
    location: 'Banten',
    created_at: '2022-02-22',
    price: 1620000,
    rating: 4,
    type: 'Paid',
    status: 'Tersedia Sekarang',
  },
];
