import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { Footer } from '@/app/(costumer)/_components/Footer';
import { FilterModalProvider } from '@/components/providers/filter-modal-provider';
import { Header } from './_components/Header';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`h-full bg-slate-100 ${inter.className}`}>
        <FilterModalProvider />
        <Header />
        <main className="pb-20 bg-slate-100">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
